project:
  type: website

website:
  title: "econWeb"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

